### ISSUE TITLE
Refreshing list of available printers

### ISSUE THREAD

**Issue by filippsudanov** [namiltd/winprint#1]
Hi!

Looks that list of printers is only updated when winprint starts. In my use case users are connecting via RDP which brings new printer to the system. Windows makes this printer as default, but winprint is not able to print. 
Could it be possible to add periodic refresh of printer list while the program runs?

**Comment by namiltd** [comment]
Printing should work correctly if you use the default printer in the application and it also changes after RDP connection.

**Comment by namiltd** [comment]
Try new version: https://github.com/namiltd/winprint/releases/download/v1.5.0.60/WinPrint-1.5.0.60-bin.zip
Select your default printer. In this version, it should change itself to a new default one after establishing an RDP connection.
